### ISSUE TITLE
Support tagging feedback

### ISSUE THREAD

**Issue by virajmehta** [tensorzero/tensorzero#127]
For example: labeler name for demonstrations, synthetic data algorithm, customer ID

**Comment by GabrielBianconi** [comment]
Start with a brief proposal

**Comment by virajmehta** [comment]
Proposal:

For each of DemonstrationFeedback, FloatMetricFeedback, CommentFeedback, BooleanMetricFeedback:

add a column `tags: Map(String, String)`. 

Add a table MetricTags
metric_name: String,
tag_key: String,
tag_value: String,
feedback_id: UUID,
tag_id: UUID,
timestamp: Materialized from tag_id,

Add materialized views to MetricTags that include all tags as separate rows from each of the feedback tables.

**Comment by GabrielBianconi** [comment]
No `feedback_id` and `timestamp`
