### ISSUE TITLE
Integrate with the Hyperbolic Labs API for inference

### ISSUE THREAD

**Issue by virajmehta** [tensorzero/tensorzero#272]

**Comment by hk1997** [comment]
Hi,
I'm new to the project and would like to pick up this issue.
Can you guide me on the exact set of requirements?

**Comment by GabrielBianconi** [comment]
Hi @hk1997 - thank you for offering to contribute!

The core functionality needed:

* Create a new provider in `gateway/src/inference/providers`
* Add the necessary entries to `gateway/src/model.rs` and `gateway/src/error.rs`
* Add your provider to the E2E test suite: `gateway/tests/e2e/providers`
* Add a minimal example to `examples/guides/providers`

We'd be happy to help with any of these. Feel free to ask here or on Slack/Discord.

(See #529 for a live PR integrating xAI - the PR is almost ready.)

Thanks!

**Comment by hk1997** [comment]
@GabrielBianconi I see that there are 3 modes of operations supported by Hyperbolic API: https://docs.hyperbolic.xyz/docs/rest-api
1. Text generation
2. Image generation
3. Audio generation

Do we plan to support all 3 or we are focussed primarily on text generation.

Asking the above question as it may decide the design choice for the Request struct used to query the API.

**Comment by virajmehta** [comment]
@hk1997 hey for now we're only doing text generation. Multimodality is definitely on our roadmap but you shouldn't consider it for this work.
