### ISSUE TITLE
Add Dynamic In-Context Learning variant type

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#286]

**Comment by virajmehta** [comment]
Plan: 
- implement (in a file) a good template for demonstrations that works with the TensorZero data model.
- write a migration that sets up the table for DICLs
Proposed Schema:

CREATE TABLE DiclExamples
(
    input String,
    output String,
    function_name LowCardinality(String),
    variant_name LowCardinality(String),
    embedding Array(Float32)
)
ENGINE = MergeTree()
PRIMARY KEY (function_name, variant_name);

- cp -r haikus and use that as the initial example. 
- write a notebook that queries for either demonstrations or successful inferences and writes to the DiclExamples table

write DICLs in Python
try the haiku performance when doing retrieval with templating or with raw inputs / outputs

write an embedding model thing in TensorZero (only support OpenAI for now), add tests (PR this separately)


write DICLs in Rust (PR this separately)

**Comment by virajmehta** [comment]
Summary of 7pm discussion:

- User can configure DICLs with `system_instructions.txt` or similar that gets templated into a system template that we hardcode.
That template contains:

those instructions,
system_, user_, assistant_ schemas if present
general description of the few-shot learning setup we are using.

Each example is a pair of a json of this form as a user message:
```
{
            "system": "You are a helpful assistant.",
            "messages": [
                {"role": "user", "content": "What's the weather like today?"},
                {"role": "assistant", "content": "it's 75 and sunny"},
                {"role": "user", "content": "Is it gonna rain?"}
            ]
        }
```
that is compliant with the schemas in the user message

and the output in the native output format(tool call, chat assistant message, etc)  (potentially several messages for someone like OpenAI, though that won't be handled at the Variant level). 

These will alternate (one pair per example).
The final message will consist of just the input of the current request in a single user message.
