### ISSUE TITLE
Add a complete RAG example

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#290]

**Comment by GabrielBianconi** [comment]
Start with a brief proposal

**Comment by virajmehta** [comment]
Proposal: take the Wikipedia dataset from [pinecone datasets](https://docs.pinecone.io/guides/data/use-public-pinecone-datasets) and use it with either Qdrant or PGVector in a local container. Then run BeerQA against it with 2 functions for query rewriting and generation and then 1 more for evaluation.

**Comment by GabrielBianconi** [comment]
`pinecone-datasets` is unlicensed so we can't use it as is. We should find something similar, or get permission from them.

**Comment by GabrielBianconi** [comment]
https://modal.com/blog/embedding-wikipedia
