### ISSUE TITLE
Best-of-N sampling doesn't correctly handle JSON mode for Anthropic models

### ISSUE THREAD

**Issue by virajmehta** [tensorzero/tensorzero#338]
3 options to fix:
1. add a check that if the model being called is Anthropic then we use ImplicitTool. 
2. Make JSON model default to ImplicitTool for Anthropic 
3. Add the Anthropic prefill thing to the implementation as in #133

**Comment by GabrielBianconi** [comment]
Let's solve via #133

**Comment by virajmehta** [comment]
Anthropic JSON mode enforcement is flaky and in particular has an issue where it generates multiline strings. This is an issue generally and in particular for "thinking" blocks. For now I don't think this is solvable. Consider deprioritizing.

**Comment by GabrielBianconi** [comment]
If this is not actionable, I'll close for now and we'll hope that Anthropic adds more JSON capabilities. It's already better than before with TensorZero's implicit tool use.
