### ISSUE TITLE
Consider adding more data to ClickHouse so it's self-sufficient

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#349]
Right now the data on ClickHouse requires the config file to reconstruct the original inference and so on. Maybe we should add enough data to ClickHouse to make entries self-sufficient.

**Comment by virajmehta** [comment]
Nik also wants this for ClickHouse

**Comment by virajmehta** [comment]
After some thought, I think the source of truth should remain the TOML file and it is the gateway's job on startup to make sure that the clickhouse tables are consistent with the TOML file.

**Comment by virajmehta** [comment]
Proposal:

modify `ProviderInferenceResponse` to contain:
```rust
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct ProviderInferenceResponse {
    pub id: Uuid,
    pub created: u64,
    pub content: Vec<ContentBlock>,
    pub system: Option<String>, // new
    pub messages: Vec<RequestMessage>, // new
    pub raw_request: String,
    pub raw_response: String,
    pub usage: Usage,
    pub latency: Latency,
}
```
modify `ModelInferenceResponse` to contain
```rust
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct ModelInferenceResponse<'a> {
    pub id: Uuid,
    pub created: u64,
    pub content: Vec<ContentBlock>,
    pub raw_request: String,
    pub raw_response: String,
    pub system: Option<String>, // new
    pub messages: Vec<RequestMessage>, // new
    pub usage: Usage,
    pub latency: Latency,
    pub model_provider_name: &'a str,
}
```

modify `ModelInferenceRequestWithMetadata` to contain
```rust
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct ModelInferenceResponseWithMetadata<'a> {
    pub id: Uuid,
    pub created: u64,
    pub content: Vec<ContentBlock>,
    pub raw_request: String,
    pub raw_response: String,
    pub system: Option<String>, // new
    pub messages: Vec<RequestMessage>, // new
    pub usage: Usage,
    pub latency: Latency,
    pub model_provider_name: &'a str,
    pub model_name: &'a str,
}
```

modify `ModelInferenceDatabaseInsert` to contain
```rust
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct ModelInferenceDatabaseInsert {
    pub id: Uuid,
    pub inference_id: Uuid,
    pub raw_request: String,
    pub raw_response: String,
    pub system: Option<String>, // new
    pub messages: Vec<RequestMessage>, // new
    pub content: Vec<ContentBlock>, // new
    pub input_tokens: u32,
    pub output_tokens: u32,
    pub response_time_ms: u32,
    pub model_name: String,
    pub model_provider_name: String,
    pub ttft_ms: Option<u32>,
}
```
to allow for this, we'll need to add String columns system, messages, and content. We should consider making `system` nullable if we need to distinguish Some("") from None (I am not sure that we do).

here's a possible ClickHouse command:

```sql
ALTER TABLE tensorzero.ModelInference
ADD COLUMN system String,
ADD COLUMN messages String,
ADD COLUMN content Nullable(String);
```

We'll also need to change the trait signature for infer_stream in ModelProvider to return a struct in place of the current string that includes `raw_request`, `messages`, and `content` for the bookkeeping (probably as owned data and will require a `clone` over messages, system). These could be as Rust types or strings really. I am inclined towards strings as the intermediate representation (with the clone / serialization happening in the struct's new() method).
