### ISSUE TITLE
Investigate: gateway does not 400 on added fields in `input`

### ISSUE THREAD

**Issue by virajmehta** [tensorzero/tensorzero#372]
We should

**Comment by virajmehta** [comment]
failed to replicate this on my end -- will try and write some tests to cover various of these cases but this is not as urgent as I originally thought

**Comment by GabrielBianconi** [comment]
Possibly related to #492?

**Comment by GabrielBianconi** [comment]
I believe #492 solved it, so I'll close now. Please feel free to re-open if the issue persists.
