### ISSUE TITLE
implement Anthropic `disable_parallel_tools` flag

### ISSUE THREAD

**Issue by virajmehta** [tensorzero/tensorzero#383]

**Comment by hk1997** [comment]
Hi,
I would like to pick this feature.
From what I understand we are trying to support the following functionality: https://docs.anthropic.com/en/docs/build-with-claude/tool-use#disabling-parallel-tool-use

The issue calls for changes in gateway/src/tool.rs & anthropic provider if I'm understanding this correctly.

**Comment by GabrielBianconi** [comment]
@hk1997 yes!

**Comment by hk1997** [comment]
@GabrielBianconi I reckon we can mark this issue as closed since https://github.com/tensorzero/tensorzero/pull/557 is merged.

**Comment by GabrielBianconi** [comment]
Thank you for the contribution @hk1997!
