### ISSUE TITLE
Support OIDC authentication?

### ISSUE THREAD

**Issue by cboettig** [tensorzero/tensorzero#412]
Can tensorzero support authentication with OIDC, like LiteLLM does?  In our academic context OpenID Connect is a critical feature for us.  Thanks!

**Comment by GabrielBianconi** [comment]
Hi @cboettig - we don't support OIDC yet. Could you share more details about how you use it / what you need? Do you have any specific providers in mind? We can explore adding this functionality soon.

Thanks for the feedback!

**Comment by cboettig** [comment]
Thanks @GabrielBianconi , definitely.  We're currently using LiteLLM as our front-end to serve researchers and students accessing a variety of (mostly open weight/open source) models exposed through VLLM instances.  Your benchmarks comparing to LiteLLM definitely caught my eye!  

I  think we want to support an open ecosystem that makes it easy to serve models from the university clusters to researchers and students, while also making it easy for research teams to add new models and compare across models. LiteLLM has been working pretty well for this scope, but I think we're starting to bump up against it's limitations and keen to explore other open source projects in this space.  A bit more background/context here https://ucsd-prp.gitlab.io/userdocs/ai/llm-managed/.

**Comment by GabrielBianconi** [comment]
Thank you for the context @cboettig!

We're open to exploring adding native support for OIDC to our gateway, but maybe a better solution would be to pair it with a dedicated open-source OIDC auth layer. The users wouldn't access the TensorZero Gateway directly but instead connect via a reverse proxy or middleware that then forwards authenticated connections to TensorZero. The advantage is that you'll get a battle-tested OIDC solution that supports the complete protocol and all sorts of features you might need for auth. There are many high-performance OSS solutions, so this should add negligible latency and overhead.

Here's an option: https://github.com/oauth2-proxy/oauth2-proxy

It'd look something like:
 
```
     ┌─────────────────┐
     │   Researcher    │
     │   or Student    │
     └────────┬────────┘
              │
              │
┌─────────────┼───────────────┐
│             │               │
│             ▼               │
│    ┌───────────────────┐    │
│    │    OIDC Proxy     │    │
│    │(e.g. oauth2-proxy)│    │
│    └────────┬──────────┘    │
│             │               │
│             ▼               │
│    ┌─────────────────┐      │
│    │   TensorZero    │      │
│    │    Gateway      │      │
│    └────────┬────────┘      │
│             │               │
│             ▼               │
│    ┌─────────────────┐      │
│    │      vLLM       │      │
│    └─────────────────┘      │
│                             │
└───── University Cluster ────┘
```

Would something like this work for you? If so, I'd be happy to write an example like the one above.

**Comment by cboettig** [comment]
thanks.  One thing that's been very helpful for us though in LiteLLM is it's ability to mint and manage tokens for different groups and different models (e.g. https://docs.litellm.ai/docs/proxy/self_serve).  e.g. an authenticated user can mint and revoke access tokens which can be scoped to access different models or groups of models, potentially with things like rate-limits or token caps on use.  But maybe that's all out-of-scope for tensorzero?

**Comment by GabrielBianconi** [comment]
Unfortunately, that sort of functionality is out of scope _for now_. That said, I understand the use case, so we'll keep you posted as we make progress in this direction!

Thanks @cboettig!
