### ISSUE TITLE
JSON Schema parsing errors are unhelpful

### ISSUE THREAD

**Issue by virajmehta** [tensorzero/tensorzero#436]
Desired experience: point at exactly where in the schema an error is present. 

c.f. @nikcaryo

**Comment by nikcaryo-super** [comment]
yeah since everything is so typed I feel like the errors here could be awesome - but instead it's a huge wall of the whole schema dumped out. probably particularly messy with some recursive schema stuff we have going on.

**Comment by GabrielBianconi** [comment]
@virajmehta FYI this would be solved by `serde_path_to_error` but it has a bug that affects us, see #335.

**Comment by virajmehta** [comment]
@GabrielBianconi disagree I think this is actually already solved with JSONschema. Our current code does this:

```
pub fn validate(&self, instance: &serde_json::Value) -> Result<(), Error> {
        self.compiled
            .validate(instance)
            .map_err(|e| Error::JsonSchemaValidation {
                messages: e
                    .into_iter()
                    .map(|error| error.to_string())
                    .collect::<Vec<String>>(),
                data: Box::new(instance.clone()),
                schema: Box::new(self.value.clone()),
            })
    }
    ```
    
    
    ```
    Error::JsonSchemaValidation {
                messages,
                data,
                schema,
            } => {
                write!(
                    f,
                    "JSON Schema validation failed for Function:\n\n{}",
                    messages.join("\n")
                )?;
                write!(
                    f,
                    "\nData: {}",
                    serde_json::to_string(data).map_err(|_| std::fmt::Error)?
                )?;
                write!(
                    f,
                    "Schema: {}",
                    serde_json::to_string(schema).map_err(|_| std::fmt::Error)?
                )
            }
            ```
            
            so we include the error from the JSONSchema crate, the data, and the schema itself. This would result in a really long error message if the data / schema are large (and maybe we should remove this) but it does contain a useful error message first.

**Comment by virajmehta** [comment]
Honestly I think the correct solution in this codebase is to "attach" function_name, variant_name, and other globally relevant parameters to errors as they are propagated up to the HTTP client. I am pretty sure there's a neat way to do this in Rust. Will look into it.
