### ISSUE TITLE
Gateway only supports (and requires) one credential per provider 

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#448]
**Update:**

Following our discussion, we'll add the credential variables to the TOML. For each of those fields, we'll have the format `env::ENV_VAR_NAME` to read from. Later we can use prefixes for other methods (secrets managers, etc.).

Default behavior (no need to specify)

```
[models.o1-mini.providers.openai]
type = "openai"
model_name = "o1-mini"
# Defaults to: api_key_source = "env::OPENAI_API_KEY"
```

If you have multiple keys:

```
[models.o1-mini.providers.openai]
type = "openai"
model_name = "o1-mini"
api_key_source = "env::MY_OTHER_OPENAI_API_KEY"
```

If authentication is not needed (e.g. local LLM), use the special value `ignore`:

```
[models.o1-mini.providers.openai]
type = "openai"
model_name = "o1-mini"
api_key_source = "ignore"
```

---

**Old issue:**

Authentication for vLLM is optional, but the gateway always requires `VLLM_API_KEY` to be set.

a) Add an ~ `disable_auth = true/false` to the provider config, check selectively.
b) Always optional, don't throw an error if env var is not empty
c) Always mandatory, user specifies anything (e.g. `VLLM_API_KEY=" "`) and it's ignored (must confirm behavior when auth is off but a key is sent)

I prefer (a).

**Comment by virajmehta** [comment]
I think I prefer (a) too

**Comment by GabrielBianconi** [comment]
Following our discussion, we'll add the credential variables to the TOML. For each of those fields, we'll have the format `env::ENV_VAR_NAME` to read from. Later we can use prefixes for other methods (secrets managers, etc.).

Default behavior (no need to specify)

```
[models.o1-mini.providers.openai]
type = "openai"
model_name = "o1-mini"
# Defaults to: api_key = "env::OPENAI_API_KEY"
```

If you have multiple keys:

```
[models.o1-mini.providers.openai]
type = "openai"
model_name = "o1-mini"
api_key = "env::MY_OTHER_OPENAI_API_KEY"
```
