### ISSUE TITLE
Add `mypy` to `pre-commit` and/or PR checks

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#490]

**Comment by virajmehta** [comment]
@GabrielBianconi is [this](https://github.com/tensorzero/tensorzero/blob/8c5313da92389756be6e063302746cb89ca7378f/.github/workflows/merge-queue.yml#L86) not what you mean?

**Comment by GabrielBianconi** [comment]
Yeah but that's too late - we should either do this with `pre-commit` or commit checks in PR as well.

**Comment by GabrielBianconi** [comment]
Merging into #515
