### ISSUE TITLE
Add a `table_exists` helper function for ClickHouse migrations

### ISSUE THREAD

**Issue by virajmehta** [tensorzero/tensorzero#494]

**Comment by GabrielBianconi** [comment]
**Good First Issue:** Many migrations [here](https://github.com/tensorzero/tensorzero/blob/main/gateway/src/clickhouse_migration_manager/migrations/) re-implement the functionality to check if a table exists in ClickHouse. We can abstract that as a helper function and use that repeatedly across migrations.
