### ISSUE TITLE
Ambiguities and Limitations in the TOML Configuration File

### ISSUE THREAD

**Issue by Matheussoranco** [tensorzero/tensorzero#533]
In the tensorzero.toml configuration file, I noticed some ambiguities that could cause difficulties for new users or lead to integration issues with external providers, such as OpenAI. 

The Model Configuration: The model gpt_4o_mini_2024_07_18 is well-defined, but there is a lack of detailed explanations about the expected values for parameters like routing and type and i think its missing an automatic validation. There seems to be no validation or auxiliary scripts ensuring that the TOML configurations are interpreted correctly, which could lead to runtime errors that cause a headache.

Maybe Add some documentation to provide detailed examples and descriptions for each field in the TOML file, explaining expected values and use cases and I really think it should be Implemented an automatic Validation, Introducing a script to verify configurations before running the code to prevent misconfigs.

**Comment by virajmehta** [comment]
Thanks for the issue! First off: did you check out our [configuration reference](https://www.tensorzero.com/docs/gateway/configuration-reference)? We've attempted to be as comprehensive as possible there but definitely appreciate that it could be better and would love any specific feedback you could give. 

Second: One medium-term goal for us is to decouple the config validation and parsing from the rest of the gateway binary to some extent. This could be especially valuable for: 
- python libraries that are config-aware and can validate a config with e.g. `uv run tensorzero validate config/tensorzero.toml` -type workflows
- UI code which can tell you whether there are errors in the config

Appreciate the feedback and also feel free to ask questions here or on [Slack](https://tensorzero.com/slack) about your particular config. We're happy to help.

**Comment by Matheussoranco** [comment]
Great! Sorry, i've missed the configuration reference on the documentation. As for the decoupling the config validation, i think that the goal you've set can solve the specific problem i've meant to show together with the gateway validation.
For more lay users and beginners in the environment, the explanatory UI would be of great help, given the more technical documentation, despite it being clear.
