### ISSUE TITLE
Add a sidebar to the dashboard

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#594]
![CleanShot 2024-12-25 at 13 26 10@2x](https://github.com/user-attachments/assets/74bf54dc-1a17-4b71-8bb6-d76e5a3fb094)

https://v0.dev/chat/QFYnJErdFP5?b=b_f7E8r40FX0e

Reference: https://ui.shadcn.com/docs/components/sidebar

**Comment by ChetanXpro** [comment]
Hey @GabrielBianconi, I can help with building the sidebar. I have good experience with layouts and frontend. Let me know if you'd like me to proceed and if there's any info I should know.

**Comment by GabrielBianconi** [comment]
Hi @ChetanXpro sounds good! Let's start with the sidebar and we can add more stuff incrementally (e.g. #595 is similar).

You can use the code generated on v0.dev above as a starting point. We are using RemixJS (now React Router V7) and shadcn.

Thanks!

**Comment by GabrielBianconi** [comment]
Hi @ChetanXpro sounds good! Let's start with the sidebar and we can add more stuff incrementally (e.g. #595 is similar).

You can use the code generated on v0.dev above as a starting point. It should have pretty much all the code you need, it just needs to be integrated into the existing files. We are using RemixJS (now React Router V7) and shadcn.

The observability links are missing for now so we can put a placeholder `#` link there.

Thanks!

**Comment by GabrielBianconi** [comment]
@ChetanXpro Actually here's an updated v0 link that also has a "collapse sidebar" button:

https://v0.dev/chat/QFYnJErdFP5?b=b_f7E8r40FX0e

**Comment by ChetanXpro** [comment]
Is this fine?

<img width="1438" alt="Screenshot 2024-12-26 at 12 50 14 AM" src="https://github.com/user-attachments/assets/07017665-6a8d-443e-aab3-c97a1197f5bf" />

**Comment by GabrielBianconi** [comment]
@ChetanXpro I think that's close!

* Let's remove "Help" and leave just "Documentation", to open `https://www.tensorzero.com/docs` in a new window.
* Navigation looks good!
* The separators you added look good!
* For the logo/TensorZero, let's change it slightly so that:

No hover:
![CleanShot 2024-12-25 at 14 34 08@2x](https://github.com/user-attachments/assets/7a1ce324-7452-4506-9298-922ea476ab93)

With hover:
![CleanShot 2024-12-25 at 14 34 55@2x](https://github.com/user-attachments/assets/643b0f2e-c94c-4927-b0f3-9a99142deacd)

(Like the [behavior on v0](https://v0.dev/chat/QFYnJErdFP5?b=b_f7E8r40FX0e).)

---

Does the collapsed version look like this?

![CleanShot 2024-12-25 at 14 35 36@2x](https://github.com/user-attachments/assets/aa7b5881-3175-429a-9ee5-cf1622e9721a)

Feel free to send a PR too and I'll play with it. Thanks for the help!

**Comment by ChetanXpro** [comment]
I have added a hover effect, and yup, the collapse version looks similar to your screenshot.

https://github.com/tensorzero/tensorzero/pull/600
