### ISSUE TITLE
Add a simple home page to the dashboard

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#595]
We can start with a very simple home page. Later we'll add more information, metrics, etc.

![CleanShot 2024-12-24 at 16 41 59@2x](https://github.com/user-attachments/assets/c1e74887-5946-4239-8e9e-4d26f372646d)

https://v0.dev/chat/MjOv5O0HwV9?b=b_vwIdC2Dh2Dd

The sidebar (#594) should also show up.

**Comment by ChetanXpro** [comment]
Would it be alright if I take this up?

**Comment by ChetanXpro** [comment]
I improved the UI little bit, like added logo etc and aligned properly. 

PR: #616 

<img width="1440" alt="Screenshot 2024-12-27 at 1 42 30 AM" src="https://github.com/user-attachments/assets/36aadf71-4443-4dd3-bf4e-2178694878a0" />
