### ISSUE TITLE
Add a `prettier` configuration file

### ISSUE THREAD

**Issue by GabrielBianconi** [tensorzero/tensorzero#691]
* Let's ensure that we're using consistent versions of `prettier` everywhere (`package.json`, `pre-commit`, Github Actions)
* Let's set up [`prettier-plugin-tailwindcss`](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier) and clean up existing files
* Let's set up the `npm format` and `npm lint` commands as well.

**Comment by GabrielBianconi** [comment]
Hey @ChetanXpro - thanks for the suggestion, would you like to tackle this one? Thanks!

**Comment by ChetanXpro** [comment]
> Hey @ChetanXpro - thanks for the suggestion, would you like to tackle this one? Thanks!

Sure, I can take this one.

**Comment by ChetanXpro** [comment]
Hey @virajmehta, I noticed we have a .prettierrc config file in the project root directory. should I set up an npm command to format at the root, or move this config to the dashboard and run prettier in dashboard only?

**Comment by virajmehta** [comment]
Let's run it in the dashboard only for now—down the line we'll want to build a typescript client as well but we can deal with that as it arises.
